### ISSUE TITLE
Add MVP Implementation

### ISSUE THREAD

**Issue by nikhilbansal97** [nikhilbansal97/ExoPlayer-Sample#3]
Refractor the codebase to follow Model View Presenter Architecture.

**Comment by drcabral** [comment]
This one is still open? I would like to try :)

**Comment by nikhilbansal97** [comment]
@drcabral Sure! Go ahead! 👍

**Comment by drcabral** [comment]
Hey @nikhilbansal97 , i did the refactor already in Kotlin, but there is some things that can be improved using this language. If this PR is already ok for you, i can take the other issue and do some kotlin refactor.

**Comment by nikhilbansal97** [comment]
Awesome! @drcabral
